async parallel image upload
SharinPix/einstein-box-import pull request #1
Opened 2017-09-20 13:32 UTC by kherinwork

2017-09-20 13:47 UTC, azharbeebeejaun requested changes

2017-09-20 13:47 UTC, azharbeebeejaun commented on index.js
> +// const secretUrl = 'sharinpix://55a77236-7167-455f-a146-ce2282906880:_EiLHGQM30s_TDPBr58cqA_cOM04yjfFitDnbB0tFLLyroU@kherin.ngrok.io/api/v1';
SECRET URL ! :O :O :O

2017-09-20 13:47 UTC, azharbeebeejaun commented on index.js
> +    let month =   ("0" + date.getMonth()).slice(-2);
espaces en plus

2017-09-20 13:47 UTC, azharbeebeejaun commented on index.js
> +    let csvJsonId = date.getFullYear()+'-'+month+'-'+utcdate+'-'+date.getHours()+date.getMinutes()+date.getSeconds();
manque d'espaces

2017-09-27 10:31 UTC, kevanmoothien requested changes

2017-09-27 10:31 UTC, kevanmoothien commented on lib/csv-upload.js
> +                                    setTimeout(function() {
setTimeout fires only once!!!

2017-10-26 15:40 UTC, closed without merging